input:
  - name: "Disposable Email Domains's list"
    repo_url: "https://github.com/disposable-email-domains/disposable-email-domains"
    data_url: "https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf"
    type: "repo"
  - name: "Disposable's email strict list"
    repo_url: "https://github.com/disposable/disposable-email-domains"
    data_url: "https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains_strict.txt"
    type: "repo"
  - name: "TheDahoom's mail blacklist"
    repo_url: "https://github.com/TheDahoom/disposable-email"
    data_url: "https://raw.githubusercontent.com/TheDahoom/disposable-email/main/blacklist.txt"
    type: "repo"
  - name: "Eser's sanitizer-svc disposable email blocklist"
    repo_url: "https://github.com/eser/sanitizer-svc"
    data_url: "https://raw.githubusercontent.com/eser/sanitizer-svc/main/disposable_email_blocklist.conf"
    type: "repo"
  - name: "Gerold Setz's emailondeck.com domains"
    repo_url: "https://github.com/GeroldSetz/emailondeck.com-domains"
    data_url: "https://raw.githubusercontent.com/GeroldSetz/emailondeck.com-domains/master/emailondeck.com_domains_from_bdea.cc.txt"
    type: "repo"
  - name: "Groundcat's disposable email domain list"
    repo_url: "https://github.com/groundcat/disposable-email-domain-list"
    data_url: "https://raw.githubusercontent.com/groundcat/disposable-email-domain-list/master/domains.txt"
    type: "repo"
  - name: "Jesper Nissen's disposable maildomain list"
    repo_url: "https://github.com/jespernissen/disposable-maildomain-list"
    data_url: "https://raw.githubusercontent.com/jespernissen/disposable-maildomain-list/master/disposable-maildomain-list.txt"
    type: "repo"
  - name: "Kslr's disposable email domains"
    repo_url: "https://github.com/kslr/disposable-email-domains"
    data_url: "https://raw.githubusercontent.com/kslr/disposable-email-domains/master/list.txt"
    type: "repo"
  - name: "Matt Ketmo's EmailChecker throwaway domains"
    repo_url: "https://github.com/MattKetmo/EmailChecker"
    data_url: "https://raw.githubusercontent.com/MattKetmo/EmailChecker/master/res/throwaway_domains.txt"
    type: "repo"
  - name: "Unkn0w's disposable email domain list"
    repo_url: "https://github.com/unkn0w/disposable-email-domain-list"
    data_url: "https://raw.githubusercontent.com/unkn0w/disposable-email-domain-list/main/domains.txt"
    type: "repo"
  - name: "7c's fakefilter"
    repo_url: "https://github.com/7c/fakefilter"
    data_url: "https://raw.githubusercontent.com/7c/fakefilter/main/txt/data.txt"
    type: "repo"
  - name: "Wes Bos's burner email providers"
    repo_url: "https://github.com/wesbos/burner-email-providers"
    data_url: "https://raw.githubusercontent.com/wesbos/burner-email-providers/master/emails.txt"
    type: "repo"
  - name: "FGRibreau's mailchecker"
    repo_url: "https://github.com/FGRibreau/mailchecker"
    data_url: "https://raw.githubusercontent.com/FGRibreau/mailchecker/master/list.txt"
    type: "repo"
  - name: "Will White's freemail"
    repo_url: "https://github.com/willwhite/freemail"
    data_url: "https://raw.githubusercontent.com/willwhite/freemail/master/data/free.txt"
    type: "repo"
  - name: "Sublime Security's static-files disposable email providers"
    repo_url: "https://github.com/sublime-security/static-files"
    data_url: "https://raw.githubusercontent.com/sublime-security/static-files/master/disposable_email_providers.txt"
    type: "repo"
